from pydantic import BaseModel, Field, ConfigDict


# This is the "base" schema. It contains all the fields that are common
# to creating and reading an address.
class AddressBase(BaseModel):
    name: str
    latitude: float = Field(
        ..., ge=-90, le=90, description="Latitude must be between -90 and 90"
    )
    longitude: float = Field(
        ..., ge=-180, le=180, description="Longitude must be between -180 and 180"
    )


# This schema is used when a user CREATES a new address.
# It inherits all fields from AddressBase.
class AddressCreate(AddressBase):
    pass  # No new fields needed, it's the same as the base


# This schema is used when the API RETURNS an address to the user.
# It includes the 'id' which is generated by the database.
class Address(AddressBase):
    id: int

    model_config = ConfigDict(from_attributes=True)
